### ISSUE TITLE
[offtopic]: Have you considered moving nvim.d.ts to it's own package?

### ISSUE THREAD

**Issue by pheis** [jose-elias-alvarez/typescript.nvim#48] opened 2022-11-25 10:13 UTC
Hullo!

I have been pondering on moving to typescript based nvim config. Would be awesome if we would have neovim & nvim plugin related typescript typings on some package : ).

**Comment by jose-elias-alvarez** [comment] 2022-11-29 20:48
We talked about this a little bit in #31. I want to write a guide on writing Neovim plugins in TypeScript, but there's a couple of issues with TypeScriptToLua that I want to look into before doing so. In the meantime feel free to copy-paste what we have here or open a PR if you have anything you want to add.

**Comment by jose-elias-alvarez** [comment] 2022-12-10 20:44
Closing as a duplicate of #31.

**Closed by jose-elias-alvarez** 2022-12-10 20:44 UTC
